services:
  - type: web
    name: ml-prediction-app
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_1:app
